version: '3.8'

services:
  php-apache-environment:
    container_name: php-docker-container
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80